export component CloseIcon inherits Rectangle {
    in property <length> icon_size: 10px;
    in property <color> icon_color: #ffffffa0;
    in property <length> stroke_width: 1.5px;

    width: root.icon_size;
    height: root.icon_size;

    Path {
        width: 100%;
        height: 100%;
        stroke: root.icon_color;
        stroke-width: root.stroke_width;

        MoveTo { x: 0; y: 0; }
        LineTo { x: 100; y: 100; }
        MoveTo { x: 100; y: 0; }
        LineTo { x: 0; y: 100; }
    }
}
